# Site settings
title: Klientbaserad webbprogrammering
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a part of the first exam in Client based webprogramming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zerorequiem.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 2

# Build settings
markdown: kramdown
